  # tasks-config.yml
  settings:
    - logLevel: info
  tasks:
    - name: Task1
      function: 'example/task1.js'
      conditions:
      - type: 'gt'
        property: 'dataValue'
        threshold: 150
